events {
    worker_connections 1024;  # Adjust the number of worker connections if necessary
}

http {
    server {
        listen 80;

        server_name llsoftware.co;  # Your domain name

        root /root/process/llsoftware/build;  # Replace with the absolute path to your 'dist' folder

        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        # Optionally, you can add caching headers for static files
        location ~* \.(jpg|jpeg|png|gif|css|js|ico|woff|woff2|eot|ttf|svg|otf)$ {
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }
    }
}
