apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-new
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sayjeyhi@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-new
    solvers:
      - http01:
          ingress:
            class: traefik
