apiVersion: apps/v1
kind: Deployment
metadata:
  name: llsoftware
  labels:
    app: llsoftware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llsoftware
  template:
    metadata:
      labels:
        app: llsoftware
    spec:
      containers:
        - name: llsoftware
          image: ghcr.io/sayjeyhi/llsoftware:latest
          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits:
              cpu: '256m'
              memory: '256Mi'
            requests:
              cpu: '100m'
              memory: '100Mi'
