apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llsoftware-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - llsoftware.dev
        - www.llsoftware.dev
      secretName: llsoftware-tls
  rules:
    - host: llsoftware.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: llsoftware-service
                port:
                  number: 80
