apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catshoulder-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - catshoulder.dev
        - www.catshoulder.dev
      secretName: catshoulder-tls
  rules:
    - host: catshoulder.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: catshoulder-service
                port:
                  number: 80
