apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llsoftware-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/ssl-redirect: "true"
    traefik.ingress.kubernetes.io/ssl-permanent-redirect: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - llsoftware.co
        - www.llsoftware.co
      secretName: llsoftware-tls
  rules:
    - host: llsoftware.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: llsoftware-service
                port:
                  number: 8080
    - host: www.llsoftware.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: llsoftware-service
                port:
                  number: 8080