apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-production
  namespace: default
spec:
  secretName: ssl-cert-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: llsoftware.co
  dnsNames:
    - 65.109.169.232.nip.io
    - llsoftware.co
    - www.llsoftware.co
    - www.catshoulder.dev
    - i18n.catshoulder.dev
