name: Build and Push Docker Image

on:
  push

permissions:
  contents: read
  packages: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set commit SHA short
        run: |
          echo "COMMIT_SHA_SHORT=${GITHUB_SHA::8}" >> $GITHUB_ENV
          echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Log repository name
        run: echo "Repository name: ${{ env.REPOSITORY_NAME }}"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Remove lock file
        run: rm -f bun.lock

      - name: Install dependencies
        run: bun i

      - name: Build
        run: bun run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_PAT }}  # GitHub automatically provides this secret

      - name: Verify GHCR login
        run: docker info

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPOSITORY_NAME }}:${{ env.COMMIT_SHA_SHORT }}
            ghcr.io/${{ env.REPOSITORY_NAME }}:${{ env.CURRENT_DATE }}
            ghcr.io/${{ env.REPOSITORY_NAME }}:latest
